# Generated by Django 6.0.2 on 2026-04-19 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('PAYMENT', 'Payment'), ('CERTIFICATE', 'Certificate'), ('QNA', 'Question & Answer'), ('COURSE', 'Course'), ('PAYOUT', 'Payout'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
