# Generated by Django 6.0.2 on 2026-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
