# Generated by Django 6.0.2 on 2026-03-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_is_approved_remove_course_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('certification', 'Certification')], default='free', max_length=20),
        ),
    ]
