# Generated by Django 6.0.2 on 2026-03-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='stattus',
            new_name='status',
        ),
    ]
