# Generated by Django 6.0 on 2026-02-11 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_teacher_bio_teacher_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-joined_date']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='platform',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='manager.course'),
        ),
    ]
