# Generated by Django 6.0 on 2025-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_student_batch_enrollment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='platform',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='teachers/'),
        ),
    ]
