# Generated by Django 6.0 on 2025-12-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_student_student_email_student_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='students/default_profile_image.jpg', upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='teachers/default_profile_image.jpg', upload_to='teachers/'),
        ),
    ]
