# Generated by Django 6.0 on 2026-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_enrollment_options_remove_student_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'On Going'), ('postponed', 'Postponed'), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
    ]
