# Generated by Django 5.2 on 2026-01-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_batch_id_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='joined_date',
            field=models.DateField(),
        ),
    ]
