# Generated by Django 6.0.2 on 2026-02-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorrequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddConstraint(
            model_name='instructorrequest',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_instructor_request_per_user'),
        ),
    ]
