# Generated by Django 6.0.2 on 2026-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_instructorrequest_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='demo_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
