# Generated by Django 6.0.2 on 2026-03-03 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'last_watched_at'], name='progress_le_user_id_f0db44_idx'),
        ),
    ]
